import { Montserrat, Volkhov } from "next/font/google";
import "./globals.scss";

import Header from './ui/header/header.jsx'
import FooterForm from './ui/footerform/footerform.jsx'
import Footer from './ui/footer/footer.jsx'

const montserrat = Montserrat({ 
  subsets: ["latin"],
  variable: '--font-montserrat', 
});

const volkhov = Volkhov({ 
  subsets: ["latin"],
  weight: ['400', '700'],
  variable: '--font-volkhov',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${montserrat.variable} ${volkhov.variable}`}>
      <body className="content-grid">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
